# Generated by Django 2.2.1 on 2019-06-27 10:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txnid', models.CharField(blank=True, max_length=128, null=True)),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('firstname', models.CharField(blank=True, max_length=32, null=True)),
                ('email', models.CharField(blank=True, max_length=128, null=True)),
                ('productinfo', models.CharField(default='car book', max_length=32)),
                ('phone', models.BigIntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
