# Generated by Django 2.2.1 on 2019-08-09 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pay',
            name='campkit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pay',
            name='car_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pay',
            name='chair',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pay',
            name='gas_stove',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pay',
            name='person_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pay',
            name='solar_power',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pay',
            name='table',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pay',
            name='torch',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
