# Generated by Django 2.2.1 on 2019-08-10 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0002_auto_20190809_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='pay',
            name='created',
            field=models.DateField(auto_now=True),
        ),
    ]
