# Generated by Django 2.2.1 on 2019-08-10 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0003_pay_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='pay',
            name='convenient',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pay',
            name='igst',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
