# Generated by Django 2.0.7 on 2018-10-14 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20181003_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='license_number',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
