# Generated by Django 2.0.7 on 2018-11-26 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_customer_terms_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='license_number',
            field=models.CharField(max_length=128),
        ),
    ]
