# Generated by Django 2.0.7 on 2019-01-31 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_form'),
    ]

    operations = [
        migrations.RenameField(
            model_name='form',
            old_name='ininerary',
            new_name='itinerary',
        ),
    ]
