# Generated by Django 2.0.7 on 2019-05-03 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0010_customer_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='trip_status',
            field=models.CharField(blank=True, choices=[('Lead Closed', 'Lead Closed'), ('Follow Up', 'Follow Up')], max_length=128, null=True),
        ),
    ]
