# Generated by Django 2.0.7 on 2019-05-03 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0011_customer_trip_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='trip_status',
            new_name='lead_status',
        ),
    ]
