# Generated by Django 2.2.1 on 2019-05-26 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_auto_20190526_0123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='productinfo',
            field=models.CharField(default='car book', max_length=32),
        ),
        migrations.AlterField(
            model_name='payment',
            name='txnid',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
