# Generated by Django 2.0.7 on 2019-02-08 10:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree_8_sleeping', models.IntegerField(blank=True)),
                ('degree_summer_sleeping', models.IntegerField(blank=True)),
                ('kettle', models.IntegerField(blank=True)),
                ('stove', models.IntegerField(blank=True)),
                ('plates', models.IntegerField(blank=True)),
                ('ground_tent', models.IntegerField(blank=True)),
                ('charger', models.IntegerField(blank=True)),
                ('chairs', models.IntegerField(blank=True)),
                ('foldable_table_and_chair', models.IntegerField(blank=True)),
                ('canister', models.IntegerField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
