# Generated by Django 2.0.7 on 2019-02-08 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0002_inventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
