# Generated by Django 2.2.1 on 2019-07-30 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itinerary', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itinerary',
            name='destination',
        ),
    ]
