# Generated by Django 2.0.7 on 2018-12-11 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referral', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='referral',
            old_name='User',
            new_name='user',
        ),
        migrations.AddField(
            model_name='referral',
            name='title',
            field=models.CharField(default='super', max_length=12),
            preserve_default=False,
        ),
    ]
