# Generated by Django 2.0.7 on 2018-12-12 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('referral', '0002_auto_20181211_2202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referral',
            name='title',
        ),
    ]
