# Generated by Django 2.0.7 on 2018-12-13 06:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('referral', '0003_remove_referral_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='referred',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='referral',
            name='referred_users',
            field=models.ManyToManyField(related_name='referred', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='referral',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrer', to=settings.AUTH_USER_MODEL),
        ),
    ]
