# Generated by Django 2.0.7 on 2018-12-13 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referral', '0004_auto_20181213_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='referral_link',
            field=models.CharField(default='Sad', max_length=64),
            preserve_default=False,
        ),
    ]
