# Generated by Django 2.0.7 on 2018-12-13 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referral', '0005_referral_referral_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referral',
            name='referral_link',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
