# Generated by Django 2.0.7 on 2018-12-13 06:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referral', '0006_auto_20181213_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referral',
            name='referred_users',
            field=models.ManyToManyField(blank=True, null=True, related_name='referred', to=settings.AUTH_USER_MODEL),
        ),
    ]
