# Generated by Django 2.0.7 on 2018-12-13 06:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('referral', '0007_auto_20181213_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='referred_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referred_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='referral',
            name='referred_users',
            field=models.ManyToManyField(blank=True, related_name='referred', to=settings.AUTH_USER_MODEL),
        ),
    ]
