# Generated by Django 2.0.7 on 2018-09-06 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleCheck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engine_oil_level', models.PositiveIntegerField()),
                ('brake_fluid_level', models.PositiveIntegerField()),
                ('water_level', models.PositiveIntegerField()),
                ('windscreen_washer', models.BooleanField()),
                ('seatbelts_check', models.BooleanField()),
                ('parking_brake', models.BooleanField()),
                ('clutch_gearshift', models.BooleanField()),
                ('burning_smell', models.BooleanField()),
                ('steering_alignment', models.BooleanField()),
                ('dashboard', models.BooleanField()),
                ('check_lights', models.BooleanField()),
                ('horn', models.BooleanField()),
                ('tyres', models.BooleanField()),
                ('leakage', models.BooleanField()),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_check', to='customer.Customer')),
            ],
        ),
    ]
