# Generated by Django 2.0.7 on 2018-09-16 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclecheck',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
