# Generated by Django 2.2.1 on 2019-08-11 09:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vehicle', '0001_initial_manual'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='definition',
            name='available',
        ),
        migrations.RemoveField(
            model_name='definition',
            name='check_in_date',
        ),
        migrations.RemoveField(
            model_name='definition',
            name='check_out_date',
        ),
        migrations.RemoveField(
            model_name='definition',
            name='duration',
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(blank=True, max_length=64, null=True)),
                ('check_in_date', models.DateField(blank=True, null=True)),
                ('check_out_date', models.DateField(blank=True, null=True)),
                ('duration', models.IntegerField()),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
