# Generated by Django 2.2.1 on 2019-08-11 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0002_auto_20190811_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='booked',
            field=models.BooleanField(default=False),
        ),
    ]
