# Generated by Django 2.2.1 on 2019-08-14 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0003_book_booked'),
    ]

    operations = [
        migrations.AddField(
            model_name='definition',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
