# Generated by Django 2.2.1 on 2019-08-14 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0004_definition_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='booked',
        ),
        migrations.AddField(
            model_name='book',
            name='txnid',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
