# Generated by Django 2.0.7 on 2019-02-18 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0004_vehicledefinition'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicledefinition',
            name='car_image',
            field=models.ImageField(default='ASd', upload_to='cars'),
            preserve_default=False,
        ),
    ]
