# Generated by Django 2.2.1 on 2019-08-14 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0005_auto_20190814_1422'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='definition',
            name='total',
        ),
        migrations.AddField(
            model_name='book',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
