# Generated by Django 2.0.7 on 2019-02-20 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0005_vehicledefinition_car_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicledefinition',
            name='available',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='vehicledefinition',
            name='car_image',
            field=models.ImageField(blank=True, null=True, upload_to='cars'),
        ),
        migrations.AlterField(
            model_name='vehicledefinition',
            name='car_name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='vehicledefinition',
            name='color',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='vehicledefinition',
            name='seat',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='vehicledefinition',
            name='year',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
