# Generated by Django 2.2.1 on 2019-08-14 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0006_auto_20190814_1520'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='total',
        ),
    ]
