# Generated by Django 2.0.7 on 2019-05-17 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0006_auto_20190220_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicledefinition',
            name='duration',
            field=models.IntegerField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
