# Generated by Django 2.2.1 on 2019-08-19 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0007_remove_book_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='definition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vehicle.Definition'),
        ),
    ]
