# Generated by Django 2.2.1 on 2019-08-19 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0008_book_definition'),
    ]

    operations = [
        migrations.AddField(
            model_name='definition',
            name='car_type',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
