# Generated by Django 2.2.1 on 2019-06-27 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0008_auto_20190520_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicledefinition',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
