# Generated by Django 2.2.1 on 2019-08-19 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0009_definition_car_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='booked',
            field=models.BooleanField(default=False),
        ),
    ]
