# Generated by Django 2.2.1 on 2019-06-27 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0009_vehicledefinition_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleDef',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(blank=True, max_length=64, null=True)),
                ('seat', models.CharField(blank=True, max_length=12, null=True)),
                ('year', models.CharField(blank=True, max_length=4, null=True)),
                ('available', models.BooleanField(default=False)),
                ('check_in_date', models.DateField(blank=True, null=True)),
                ('check_out_date', models.DateField(blank=True, null=True)),
                ('color', models.CharField(blank=True, max_length=12, null=True)),
                ('car_image', models.ImageField(blank=True, null=True, upload_to='cars')),
                ('duration', models.IntegerField()),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.DeleteModel(
            name='VehicleDefinition',
        ),
    ]
