# Generated by Django 2.2.1 on 2019-08-19 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0010_book_booked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='booked',
        ),
    ]
