# Generated by Django 2.2.1 on 2019-06-27 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0010_auto_20190627_1655'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicledef',
            name='active',
        ),
    ]
