# Generated by Django 2.0.7 on 2018-12-12 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blog_images',
            field=models.ImageField(blank=True, upload_to='blog_images'),
        ),
        migrations.AddField(
            model_name='blog',
            name='description',
            field=models.CharField(default='kala', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='heading',
            field=models.CharField(default='kala', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='sub_heading',
            field=models.CharField(default='lala', max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blog',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='blog',
            name='created_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='created_time',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
