# Generated by Django 2.0.7 on 2018-12-09 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blog_cover_images',
            field=models.ImageField(blank=True, upload_to='blog_cover_images'),
        ),
    ]
