# Generated by Django 2.0.7 on 2018-12-15 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20181212_2157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='created_time',
        ),
        migrations.AlterField(
            model_name='blog',
            name='blog_cover_images',
            field=models.ImageField(blank=True, upload_to='blog_images'),
        ),
    ]
