# Generated by Django 2.0.7 on 2018-12-10 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blog_blog_cover_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='heading',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='blog',
            name='sub_heading',
            field=models.CharField(max_length=30),
        ),
    ]
