# Generated by Django 2.0.7 on 2018-12-27 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='blog_image',
        ),
        migrations.AddField(
            model_name='image',
            name='blog_image1',
            field=models.ImageField(blank=True, null=True, upload_to='blog_image'),
        ),
        migrations.AddField(
            model_name='image',
            name='blog_image2',
            field=models.ImageField(blank=True, null=True, upload_to='blog_image'),
        ),
    ]
