# Generated by Django 2.0.7 on 2018-12-27 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20181227_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='blog_image1',
            field=models.ImageField(blank=True, default='asd', upload_to='blog_image'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='image',
            name='blog_image2',
            field=models.ImageField(blank=True, default='asd', upload_to='blog_image'),
            preserve_default=False,
        ),
    ]
