# Generated by Django 2.0.7 on 2019-01-31 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20181227_2024'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referral', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=64)),
                ('phone', models.CharField(max_length=64)),
                ('email', models.CharField(max_length=64)),
                ('driving', models.CharField(max_length=64)),
                ('food', models.CharField(max_length=64)),
                ('sleep', models.CharField(max_length=64)),
                ('anything', models.CharField(max_length=64)),
            ],
        ),
    ]
