# Generated by Django 2.0.7 on 2019-03-05 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='slug',
            field=models.SlugField(default='x', max_length=40),
            preserve_default=False,
        ),
    ]
