# Generated by Django 2.2.1 on 2019-09-05 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_password_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='password',
            name='used',
            field=models.BooleanField(default=False),
        ),
    ]
