# Generated by Django 2.2.1 on 2019-09-05 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_password_used'),
    ]

    operations = [
        migrations.RenameField(
            model_name='password',
            old_name='initiate_time',
            new_name='initiate_date',
        ),
    ]
