# Generated by Django 2.2.1 on 2019-07-13 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('distance', models.IntegerField()),
                ('hours', models.IntegerField()),
                ('accommodation', models.CharField(max_length=64)),
                ('important_to_know', models.CharField(max_length=128)),
                ('night_time_temperature', models.IntegerField()),
                ('season', models.CharField(max_length=64)),
                ('slug', models.SlugField(blank=True, max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(blank=True, max_length=128, null=True)),
                ('longitude', models.FloatField(blank=True, max_length=128, null=True)),
                ('images', models.ImageField(blank=True, upload_to='maps/image')),
                ('iconImage', models.ImageField(blank=True, upload_to='maps/iconImage')),
                ('title', models.CharField(blank=True, max_length=64, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='destination.Destination')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='destination.Destination')),
                ('region', models.ManyToManyField(related_name='Region', to='destination.Map')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(blank=True, upload_to='maps/detail')),
                ('image2', models.ImageField(blank=True, upload_to='maps/detail')),
                ('image3', models.ImageField(blank=True, upload_to='maps/detail')),
                ('image4', models.ImageField(blank=True, upload_to='maps/detail')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='destination.Destination')),
            ],
        ),
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_land', models.CharField(max_length=64)),
                ('accessible_By', models.CharField(max_length=64)),
                ('check_in', models.CharField(max_length=64)),
                ('check_out', models.CharField(max_length=64)),
                ('cancellation_policy', models.CharField(max_length=64)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='destination.Destination')),
            ],
        ),
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basic_toilet', models.CharField(default='No', max_length=64)),
                ('bathroom', models.CharField(default='No', max_length=64)),
                ('kitchen', models.CharField(default='No', max_length=64)),
                ('pets_allowed', models.CharField(default='No', max_length=64)),
                ('charging_points', models.CharField(default='No', max_length=64)),
                ('drinking_water', models.CharField(default='No', max_length=64)),
                ('covered_area', models.CharField(default='No', max_length=64)),
                ('barbeque_grills', models.CharField(default='No', max_length=64)),
                ('good_for_groups', models.CharField(default='No', max_length=64)),
                ('campfire', models.CharField(default='No', max_length=64)),
                ('picnic_table', models.CharField(default='No', max_length=64)),
                ('breakfast', models.CharField(default='No', max_length=64)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='destination.Destination')),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('off_roading', models.CharField(default='No', max_length=64)),
                ('trekking', models.CharField(default='No', max_length=64)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='destination.Destination')),
            ],
        ),
    ]
