# Generated by Django 2.0.7 on 2018-10-02 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('activities', models.TextField()),
                ('distance', models.IntegerField()),
                ('hours', models.IntegerField()),
                ('images', models.ImageField(blank=True, upload_to='pics')),
            ],
        ),
    ]
