# Generated by Django 2.0.7 on 2018-10-04 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destination', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='images',
            field=models.ImageField(blank=True, upload_to='destination'),
        ),
    ]
