# Generated by Django 2.0.7 on 2019-03-08 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destination', '0002_auto_20181004_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='slug',
            field=models.SlugField(blank=True, max_length=40, null=True),
        ),
    ]
