# Generated by Django 2.2.1 on 2019-07-13 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destination', '0002_auto_20190713_1408'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='night_time_temperature',
        ),
        migrations.AddField(
            model_name='destination',
            name='night_time_temperature_summer',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='destination',
            name='night_time_temperature_winter',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
