# Generated by Django 2.2.1 on 2019-07-13 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destination', '0003_auto_20190713_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='night_time_temperature_summer',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='destination',
            name='night_time_temperature_winter',
            field=models.CharField(max_length=64),
        ),
    ]
