# Generated by Django 2.2.1 on 2019-07-31 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destination', '0005_activity_boating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amenity',
            name='barbeque_grills',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='amenity',
            name='basic_toilet',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='amenity',
            name='bathroom',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='amenity',
            name='breakfast',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='amenity',
            name='campfire',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='amenity',
            name='charging_points',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='amenity',
            name='covered_area',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='amenity',
            name='drinking_water',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='amenity',
            name='good_for_groups',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='amenity',
            name='kitchen',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='amenity',
            name='pets_allowed',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='amenity',
            name='picnic_table',
            field=models.BooleanField(),
        ),
    ]
