# Generated by Django 2.2.1 on 2019-07-31 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destination', '0006_auto_20190731_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='boating',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='activity',
            name='off_roading',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='activity',
            name='trekking',
            field=models.BooleanField(),
        ),
    ]
