# Generated by Django 2.2.1 on 2019-07-31 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destination', '0007_auto_20190731_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='caving',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activity',
            name='fishing',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activity',
            name='historical_monument',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activity',
            name='jungle_walk',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activity',
            name='lake',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activity',
            name='local_farm',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activity',
            name='river_beach',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activity',
            name='swimming',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activity',
            name='waterfall',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
