# Generated by Django 2.2.1 on 2019-08-03 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destination', '0008_auto_20190731_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='cc_higlight',
            field=models.CharField(default='A', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='destination',
            name='map_loc',
            field=models.CharField(default='A', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='destination',
            name='state_city',
            field=models.CharField(default='A', max_length=64),
            preserve_default=False,
        ),
    ]
