# Generated by Django 2.2.1 on 2019-08-03 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destination', '0009_auto_20190803_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='phone',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
