# Generated by Django 2.2.1 on 2019-08-06 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('destination', '0010_detail_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='region',
            name='destination',
        ),
    ]
