# Generated by Django 2.2.1 on 2019-09-26 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destination', '0012_destination_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='Circuit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=40, null=True)),
                ('para11', models.CharField(blank=True, max_length=256, null=True)),
                ('para12', models.CharField(blank=True, max_length=256, null=True)),
                ('para13', models.TextField()),
                ('image1', models.ImageField(blank=True, upload_to='circuit')),
                ('image2', models.ImageField(blank=True, upload_to='circuit')),
                ('image3', models.ImageField(blank=True, upload_to='circuit')),
                ('image4', models.ImageField(blank=True, upload_to='circuit')),
                ('image5', models.ImageField(blank=True, upload_to='circuit')),
            ],
        ),
    ]
