# Generated by Django 2.2.1 on 2019-09-26 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destination', '0014_auto_20190926_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='circuit',
            name='main_image',
            field=models.ImageField(blank=True, upload_to='circuit'),
        ),
    ]
