# Generated by Django 2.2.1 on 2019-09-26 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destination', '0015_circuit_main_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='circuit',
            name='name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
