# Generated by Django 2.2.1 on 2019-09-29 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destination', '0016_circuit_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='important_to_know',
            field=models.TextField(),
        ),
    ]
