# Generated by Django 2.2.1 on 2019-10-05 07:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('destination', '0017_auto_20190929_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='booked',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caravan', models.IntegerField()),
                ('rooftop', models.IntegerField()),
                ('ground', models.IntegerField()),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='destination.Detail')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
