# Generated by Django 2.2.1 on 2019-10-05 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destination', '0020_auto_20191005_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='convenient',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='igst',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
