# Generated by Django 2.0.7 on 2019-01-24 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='guest',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trip',
            name='car_type',
            field=models.CharField(blank=True, choices=[('thar', 'Thar'), ('xenon2014', 'Xenon2014'), ('xenon2018', 'Xenon2018')], max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='trip_status',
            field=models.CharField(blank=True, choices=[('ended', 'Ended'), ('ongoing', 'Ongoing'), ('upcoming', 'Upcoming')], max_length=128, null=True),
        ),
    ]
