# Generated by Django 2.0.7 on 2019-01-28 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0002_auto_20190124_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='amount_paid',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='car_type',
            field=models.CharField(blank=True, choices=[('Thar', 'Thar'), ('Xenon2014', 'Xenon2014'), ('Xenon2018', 'Xenon2018')], max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='trip_status',
            field=models.CharField(blank=True, choices=[('Ended', 'Ended'), ('Ongoing', 'Ongoing'), ('Upcoming', 'Upcoming')], max_length=128, null=True),
        ),
    ]
