# Generated by Django 2.0.7 on 2019-01-29 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0003_auto_20190128_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='car_type',
            field=models.CharField(blank=True, choices=[('Thar', 'Thar'), ('Xenon 2014', 'Xenon 2014'), ('Xenon 2018', 'Xenon 2018')], max_length=64, null=True),
        ),
    ]
