# Generated by Django 2.0.7 on 2019-05-03 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0004_auto_20190129_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='lead_status',
            field=models.CharField(blank=True, choices=[('Lead Closed', 'Lead Closed'), ('Follow Up', 'Follow Up')], max_length=128, null=True),
        ),
    ]
