# Generated by Django 2.0.7 on 2019-05-03 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0005_trip_lead_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='lead_status',
        ),
    ]
