# Generated by Django 2.0.7 on 2019-05-17 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0006_remove_trip_lead_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='car_type',
            field=models.CharField(blank=True, choices=[('As 12u 8992', 'As 12u 8992'), ('Ar 01f 6925', 'Ar 01f 6925'), ('As 12u 8992', 'As 12u 8992'), ('Ml 10b 8441', 'Ml 10b 8441')], max_length=64, null=True),
        ),
    ]
